### ISSUE TITLE
Fix for command arguments in compact form (Backus-Naur Form path commands)

### ISSUE THREAD

**Issue by SmartArtsStudio** [Pomax/svg-to-something#2]
You may wish to add this line to your normalization method I had not accounted for compact path commands:
```js
d = d.replace( /((\s|\d)\.\d+)(\.\d)/g, '$1 $3' );  // consume Backus-Naur Form production until character or second decimal is encountered. https://www.w3.org/TR/SVG/paths.html#PathDataBNF
 ```

**Comment by Pomax** [comment]
Feel free to form a PR - if this fixes an actual error, probably with a small addition to test.js that fails on the current code but succeeds with your addition.

**Comment by Pomax** [comment]
closed due to inactivity
